### ISSUE TITLE
facebook 'This page isn't available right now'

### ISSUE THREAD

**Issue by quetzalsly** [hedint/vue3-social-sharing#12]
seems like there is an error with facebook but not sure if its just on my end. It comes up with that error message every time.

**Comment by hedint** [comment]
@quetzalsly 
Can you provide more info? (like the link you're trying to share and your code)
It seems to work properly in the demo
https://stackblitz.com/edit/vue3-social-sharing-plugin?file=src%2FApp.vue

**Comment by chandlerwilcox88** [comment]
I am having the same problem

**Comment by hedint** [comment]
@chandlerwilcox88
Could you provide the exact value for the url param and/or a reproduction demo in [stackblitz.com](https://stackblitz.com/)?

**Comment by chandlerwilcox88** [comment]
`url="https://domain.com/channel/12/spot/34" `

**Comment by hedint** [comment]
> Yep @hedint
> 
> `url="https://domain.com/channel/12/spot/34" `

It works for me though.
https://stackblitz.com/edit/vue3-social-sharing-plugin-c2daqe?file=src%2FApp.vue

**Comment by hedint** [comment]
Closed due to lack of the reproduction.
