### ISSUE TITLE
Describe how to add a custom network through plugin options

### ISSUE THREAD

**Issue by hedint** [hedint/vue3-social-sharing#6]

**Comment by zenonux** [comment]
same issue， i need qq

**Comment by hedint** [comment]
@zenonux 
The docs was updated, so as [the demo](https://stackblitz.com/edit/vue3-social-sharing-plugin?file=src%2Fmain.js)

**Comment by zenonux** [comment]
> @zenonux 
> 
> The docs was updated, so as [the demo](https://stackblitz.com/edit/vue3-social-sharing-plugin?file=src%2Fmain.js)

awesome
